// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEWZ4GuWvR-Naxr-lM8dQiNibHbd0_lhM',
    appId: '1:1067420921373:web:edbb4ed6f2bc95d640a0f4',
    messagingSenderId: '1067420921373',
    projectId: 'akfirst-be144',
    authDomain: 'akfirst-be144.firebaseapp.com',
    databaseURL: 'https://akfirst-be144.firebaseio.com',
    storageBucket: 'akfirst-be144.appspot.com',
    measurementId: 'G-GKLC7G8GZM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYLhM9pypxzlvDTT7dZMWzmFo9YekXjpc',
    appId: '1:1067420921373:android:8e23331776b2458640a0f4',
    messagingSenderId: '1067420921373',
    projectId: 'akfirst-be144',
    databaseURL: 'https://akfirst-be144.firebaseio.com',
    storageBucket: 'akfirst-be144.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSGcKrhoUXgAzIYZemAOzQ0mtQtOhvu40',
    appId: '1:1067420921373:ios:1b26e48d2475899340a0f4',
    messagingSenderId: '1067420921373',
    projectId: 'akfirst-be144',
    databaseURL: 'https://akfirst-be144.firebaseio.com',
    storageBucket: 'akfirst-be144.appspot.com',
    androidClientId: '1067420921373-7aum73p7n3hk86sv1gjf1v6vbo88mhpt.apps.googleusercontent.com',
    iosClientId: '1067420921373-u2v9dc0en9om3ldlh51uq5216pd52e04.apps.googleusercontent.com',
    iosBundleId: 'com.authentication.firebaseAuthenticationBloc',
  );
}
